.PHONY: clean All

All:
	@echo "----------Building project:[ KhaiRN - Debug ]----------"
	@cd "KhaiRN" && "$(MAKE)" -f  "KhaiRN.mk"
clean:
	@echo "----------Cleaning project:[ KhaiRN - Debug ]----------"
	@cd "KhaiRN" && "$(MAKE)" -f  "KhaiRN.mk" clean
